steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'asia-northeast1-docker.pkg.dev/jisong-cloud-492111/cloud-run-source-deploy/jisong-dev:$COMMIT_SHA'
      - '.'
    id: Build

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'asia-northeast1-docker.pkg.dev/jisong-cloud-492111/cloud-run-source-deploy/jisong-dev:$COMMIT_SHA'
    id: Push

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - deploy
      - 'jisong-dev'
      - '--region=asia-northeast1'
      - '--image=asia-northeast1-docker.pkg.dev/jisong-cloud-492111/cloud-run-source-deploy/jisong-dev:$COMMIT_SHA'
      - '--service-account=jisong-cloud-run@jisong-cloud-492111.iam.gserviceaccount.com'
      - '--allow-unauthenticated'
      - '--quiet'
    id: Deploy

images:
  - 'asia-northeast1-docker.pkg.dev/jisong-cloud-492111/cloud-run-source-deploy/jisong-dev:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY